---
- name: criando inventario das maquinas
  hosts: all
  tasks:
   - name: maquina CENT OS
     shell: "echo maquina centos >> /tmp/inventario "
     when: ansible_os_family == "RedHat"

   - name: maquina CENT OS
     shell: "echo maquina debian >> /tmp/inventario "
     when: ansible_os_family == "Debian"

