---

- name: instalacao DEB
  apt:
    deb:  https://apt.puppetlabs.com/puppet5-release-xenial.deb
  when: ansible_os_family == "Debian"

- name: instalacao CENT OS
  yum: 
   name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: ansible_os_family == "RedHat"

- name: instalar o puppet agent
  package:
    name:  puppet-agent
    state: present
    update_cache: yes
   
